# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=10, verbose_name='\u5355\u636e\u53f7')),
                ('sale_nums', models.IntegerField(default=0, verbose_name='\u9500\u552e\u6570')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='\u5ba2\u6237')),
                ('commodities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodities', verbose_name='\u5546\u54c1')),
            ],
        ),
    ]
