# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0011_remove_commodities_charge'),
        ('documents', '0004_auto_20180310_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='commodities',
        ),
        migrations.AddField(
            model_name='documents',
            name='merchant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commodities.FactoryToCommodity', verbose_name='\u5546\u54c1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='merchant_sums',
            field=models.IntegerField(default=0, verbose_name='\u5546\u54c1\u603b\u4ef7'),
        ),
        migrations.AddField(
            model_name='documents',
            name='ownmoney',
            field=models.IntegerField(default=0, verbose_name='\u9500\u552e\u6b20\u6b3e'),
        ),
        migrations.AddField(
            model_name='documents',
            name='payback',
            field=models.IntegerField(default=0, verbose_name='\u8fd8\u6b3e'),
        ),
        migrations.AddField(
            model_name='documents',
            name='return_nums',
            field=models.IntegerField(default=0, verbose_name='\u9000\u8d27\u6570'),
        ),
        migrations.AddField(
            model_name='documents',
            name='return_sums',
            field=models.IntegerField(default=0, verbose_name='\u9500\u552e\u603b\u4ef7'),
        ),
        migrations.AddField(
            model_name='documents',
            name='returnmerchant_sums',
            field=models.IntegerField(default=0, verbose_name='\u9000\u8d27\u5546\u54c1\u603b\u4ef7'),
        ),
        migrations.AddField(
            model_name='documents',
            name='salescharge',
            field=models.ForeignKey(default=320, on_delete=django.db.models.deletion.CASCADE, to='commodities.Charge', verbose_name='\u4ef7\u683c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='salessums',
            field=models.IntegerField(default=0, verbose_name='\u9500\u552e\u603b\u4ef7'),
        ),
    ]
