# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20180314_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='salescharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.RelateCharge', verbose_name='\u4ef7\u683c'),
        ),
    ]
