# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-15 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0011_remove_commodities_charge'),
        ('documents', '0007_auto_20180316_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_tr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=10, verbose_name='\u5355\u636e\u53f7')),
                ('classify', models.CharField(choices=[('sale', '\u9500\u8d27'), ('return', '\u9000\u8d27')], default='sale', max_length=10)),
                ('charge', models.CharField(max_length=10, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('sale_nums', models.IntegerField(default=0, verbose_name='\u6570\u91cf')),
                ('payback', models.IntegerField(default=0, verbose_name='\u8fd8\u6b3e')),
                ('salessums', models.IntegerField(default=0, verbose_name='\u9500\u552e\u603b\u4ef7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.FactoryToCommodity', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='merchant_sums',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='return_nums',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='return_sums',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='returnmerchant_sums',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='sale_nums',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='salessums',
        ),
    ]
