# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20180316_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='ownmoney',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u9500\u552e\u6b20\u6b3e'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='payback',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8fd8\u6b3e'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
