# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20180317_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='money',
            field=models.CharField(max_length=10, verbose_name='\u603b\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='ownmoney',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u9500\u552e\u6b20\u6b3e'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='payback',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u8fd8\u6b3e'),
        ),
        migrations.AlterField(
            model_name='documents_tr',
            name='payback',
            field=models.CharField(max_length=10, verbose_name='\u8fd8\u6b3e'),
        ),
        migrations.AlterField(
            model_name='documents_tr',
            name='sale_nums',
            field=models.CharField(max_length=10, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='documents_tr',
            name='salessums',
            field=models.CharField(max_length=10, verbose_name='\u9500\u552e\u603b\u4ef7'),
        ),
    ]
