# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20180317_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_tr',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commodities.FactoryToCommodity', verbose_name='\u5546\u54c1'),
        ),
    ]
