# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_documents_tr_payback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='add_time',
            field=models.DateField(default=datetime.datetime.today, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
