# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-08 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u4e61\u9547\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5730\u533a',
                'verbose_name_plural': '\u5730\u533a',
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': '\u5ba2\u6237', 'verbose_name_plural': '\u5ba2\u6237'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.AddField(
            model_name='district',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', verbose_name='\u5ba2\u6237'),
        ),
    ]
