# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20180310_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.District', verbose_name='\u4e61\u9547'),
        ),
    ]
