# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('charge', models.IntegerField(max_length=20, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('factory', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5382\u5bb6\u540d\u79f0')),
            ],
        ),
    ]
