# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-08 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_auto_20180306_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodities',
            options={'verbose_name': '\u5546\u54c1', 'verbose_name_plural': '\u5546\u54c1'},
        ),
    ]
