# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-10 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0004_auto_20180309_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5382\u5bb6\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5382\u5bb6',
                'verbose_name_plural': '\u5382\u5bb6',
            },
        ),
        migrations.AlterField(
            model_name='commodities',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Factory', verbose_name='\u5382\u5bb6'),
        ),
    ]
