# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0007_auto_20180311_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryToCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodities', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.RemoveField(
            model_name='factory',
            name='commodities',
        ),
        migrations.AddField(
            model_name='factorytocommodity',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Factory', verbose_name='\u5382\u5bb6'),
        ),
    ]
