# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0008_auto_20180311_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(verbose_name='\u5546\u54c1\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u4ef7\u683c',
                'verbose_name_plural': '\u5546\u54c1\u4ef7\u683c',
            },
        ),
        migrations.CreateModel(
            name='RelateCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Charge', verbose_name='\u4ef7\u683c')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.FactoryToCommodity', verbose_name='\u5382\u5bb6\u5546\u54c1')),
            ],
        ),
    ]
