# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0010_auto_20180312_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodities',
            name='charge',
        ),
    ]
